---
project: TMM Auto
kind: ENDPOINT
name: Prod-VKE-Cluster
description: ''
type: kubernetes:KubernetesServer
properties:
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlbW8tdXNlci10b2tlbi03cHprcyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJkZW1vLXVzZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJhNzM1NGU5ZS04ZGFkLTExZTgtYjU2YS0wNjE4ZDc3YzVlZDIiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpkZW1vLXVzZXIifQ.2rrmb_nzvd6wxP72q0a5nHgUvediZl8yIHpgQ2wpEI0O98MXYzchyzaXAnPGGg_hJYo5XUYUCY0yTULJMP7uYkShuKAag2swTAfcmUh1foSPdxJ-uwTvlFXqMlvoAiXWRXpq33YD9JVh0N06LXAAq-KK_SDTVH64i_4qauEsonOpJHN2doGmGGrG3bL3CHlopYu9V3NjpBkmNHk1fEKRGsmmvaptcRP744X5MgfBZVSfOGDFyQJE3w4O-gb0du5diPiEif3RQevMKuGGXmeofAcHrJRxfXesP-IezR5V9a3hU3i80NfPXdyku6zl_h6BkjTfKhXyqdTOdeDAXVB2oA
  authType: token
  kubernetesURL: https://api.codestream-prod-346e569c-8dac-11e8-afd7-067318bef608.20f1c3b4-f178-464f-9e82-e42eaecf2d36.vke-user.com:443
