name: vSphereStorageUC4
iteration: 1
description: 'Complete AWS-based Wordpress App with LB, Storage'
inputs: {}
resources:
  ExtDisk:
    type: Cloud.Volume
    metadata:
      layoutPosition:
        - 1
        - 2
    properties:
      capacityGb: 8
      name: External_DB_Disk
  LoadBalancer:
    type: Cloud.LoadBalancer
    metadata:
      layoutPosition:
        - 2
        - 0
    properties:
      name: wordpress-lb
      instances:
        - '${WebTier.id}'
      internetFacing: true
      network: '${ExternalNet.name}'
      routes:
        - protocol: HTTP
          port: '80'
          instanceProtocol: HTTP
          instancePort: '80'
          healthCheckConfiguration:
            protocol: HTTP
            port: '80'
            urlPath: /index.html
            intervalSeconds: 60
            timeoutSeconds: 5
            unhealthyThreshold: 5
            healthyThreshold: 2
  WebTier:
    type: Cloud.Machine
    dependsOn:
      - DBTier
    metadata:
      layoutPosition:
        - 2
        - 1
    properties:
      constraints:
        - tag: 'cloud:aws'
      flavor: small
      image: ubuntu
      count: 3
      storage:
        disks:
          - name: DISK_01
            capacityGb: 8
      cloudConfig: |
        #cloud-config
        hostname: wordpress-web
        chpasswd:
          list: |
            ubuntu:VMware1!
          expire: False
        users:
          - name: ubuntu
            passwd: "$1$Lg35t2vk$MIw6mB5VSuZsztttRGlJe0"
            lock-passwd: False
            groups: sudo
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
        repo_update: true
        repo_upgrade: all
        packages:
          - apache2
          - php
          - php-mysql
          - libapache2-mod-php
          - php-mcrypt
          - mysql-client
        runcmd:
          - touch /etc/network/interfaces.d/ens33.cfg
          - echo 'auto ens33 \r\niface ens33 inet dhcp' >> /etc/network/interfaces.d/ens33.cfg
          - /sbin/ifup ens33
          - route add default gw 192.168.209.1 ens33
          - mkdir -p /var/www/html/mywordpresssite && cd /var/www/html && wget https://wordpress.org/latest.tar.gz && tar -xzf /var/www/html/latest.tar.gz -C /var/www/html/mywordpresssite --strip-components 1
          - for i in {1..5}; do mysql --connect-timeout=3 -h ${DBTier.address} -u root -pmysqlpassword -e "SHOW STATUS;" && break || sleep 15; done
          - mysql -u root -pmysqlpassword -h ${DBTier.address} -e "create database wordpress_blog;"
          - mv /var/www/html/mywordpresssite/wp-config-sample.php /var/www/html/mywordpresssite/wp-config.php
          - sed -i -e s/"define('DB_NAME', 'database_name_here');"/"define('DB_NAME', 'wordpress_blog');"/ /var/www/html/mywordpresssite/wp-config.php && sed -i -e s/"define('DB_USER', 'username_here');"/"define('DB_USER', 'root');"/ /var/www/html/mywordpresssite/wp-config.php && sed -i -e s/"define('DB_PASSWORD', 'password_here');"/"define('DB_PASSWORD', 'mysqlpassword');"/ /var/www/html/mywordpresssite/wp-config.php && sed -i -e s/"define('DB_HOST', 'localhost');"/"define('DB_HOST', '${DBTier.address}');"/ /var/www/html/mywordpresssite/wp-config.php
          - service apache2 reload
      networks:
        - name: '${ExternalNet.name}'
      attachedDisks: []
  DBTier:
    type: Cloud.Machine
    metadata:
      layoutPosition:
        - 2
        - 2
    properties:
      flavor: small
      constraints:
        - tag: 'cloud:aws'
      image: ubuntu
      cloudConfig: |
        #cloud-config
        hostname: wordpress-mysql.sqa.local
        users:
          - name: ubuntu
            passwd: "$1$Lg35t2vk$MIw6mB5VSuZsztttRGlJe0"
            lock-passwd: False
            groups: sudo
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
        chpasswd:
          list: |
            ubuntu:VMware1!
          expire: False
        repo_update: true
        repo_upgrade: all
        packages:
         - mysql-server
        runcmd:
         - sed -e '/bind-address/ s/^#*/#/' -i /etc/mysql/mysql.conf.d/mysqld.cnf
         - service mysql restart
         - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'mysqlpassword';"
         - mysql -e "FLUSH PRIVILEGES;"
      networks:
        - name: '${ExternalNet.name}'
      attachedDisks:
        - source: '${ExtDisk.id}'
  ExternalNet:
    type: Cloud.Network
    metadata:
      layoutPosition:
        - 3
        - 0
    properties:
      name: Default AWS Networks
      networkType: existing
